### ISSUE TITLE
topic addition for better community reach

### ISSUE THREAD

**Issue by Wladefant** [huguesjohnson/RetailClerk89#5]
Hey,
for better reach of the community, I would like to suggest to add the following topic to the repository: `motorola-68000`

[How to do this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository)

**Comment by huguesjohnson** [comment]
motorola-68000 is already a topic in the about section

![image](https://user-images.githubusercontent.com/3034930/210663303-6253dc47-ffad-485d-94b1-72be84193b77.png)
